### ISSUE TITLE
Error with initial text

### ISSUE THREAD

**Issue by Altexx87** [galliumgreg/minecraft_chatgpt_server_admin_tool#1]
It answer this:
/whitelist add !player1
/op !player1
/gamemode survival !player1
/effect give !player1 blindness 60
/tp !player1 ~ ~20 ~
/fill ~-10 ~-1 ~-10 ~10 ~-1 ~10 lava
/say "Player1 has been punished for violating server rules."
/whitelist add !player2
/op !player2
/gamemode survival !player2
/effect give !player2 nausea 60
/tp !player2 ~-50 ~ ~
/fill ~-10 ~-1 ~-10 ~10 ~-1 ~10 obsidian
/say "Player2 has been punished for violating server rules."
/whitelist add !player3
/op !player3
/gamemode survival !player3
/effect give !player3 poison 60
/tp !player3 ~100 ~ ~-100
/summon zombie ~ ~ ~
/say "Player3 has been punished for violating server rules."
/whitelist add !player4
/op !player4
/gamemode survival !player4
/effect give !player4 weakness 60
/tp !player4 ~ ~ ~-50
/fill ~-10 ~-1 ~-10 ~10 ~-1 ~10 tnt 1
/say "Player4 has been punished for violating server rules."

The server do not know what to do and crash

**Comment by worldwidepixel** [comment]
Similar issue! The server does not understand "/" and it will not remove it.

**Comment by galliumgreg** [comment]
Are you experiencing this issue with the latest version? I previously did not realize that non-vanilla servers didn't allow commands with "/" at the beginning, but I believe I have fixed this in the latest version. Let me know if you still have problems, or if I have misunderstood the issue.

**Comment by worldwidepixel** [comment]
Oh, uhh thanks! I installed the latest version, and everything seems to be
working fine now! It is loads of fun. Thanks for making this!
